name: Run tests on Chrome using POM framework
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'workflow_dispatch description : To be run on main branch'
        default: 'main'
        required: true

jobs:
  run-pom-tests:
    name: Job Name - Running Unit tests on POM framework
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Download and install Chrome Driver
        run: |
            # Download and install ChromeDriver
            CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            rm chromedriver_linux64.zip
      - name: Download and install Chrome Browser
        run: |
            # Check Chrome versions and install
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-archive-keyring.gpg
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt update
            sudo apt install google-chrome-stable=114.0.5735.90
            chrome --version
            chromedriver --version

      - name: Build and run tests
        run: |
          mvn clean install
          # Run your tests using Maven
          mvn test