name: Continuous Integration to AWS instance.
run-name: Executing CI/CD by ${{github.actor}}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Java 17 installation
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Run tests
        run: mvn clean install

  analyse:
     name: Run security check
     runs-on: windows-latest
     permissions:
       actions: read
       contents: read
       security-events: write

     strategy:
       fail-fast: false
       matrix:
        language: ['java']

     steps:
       - name: Checkout
         uses:  actions/checkout@v3.5.3

       - name: Initialize CodeQL
         uses: github/codeql-action/init@v2
         with:
           languages: ${{matrix.language}}
        # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
       - name: Auto-build
         uses: github/codeql-action/autobuild@v2

       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v2
         with:
            category: "/language:${{matrix.language}}"


  push_to_ec2:
   #needs: [build]
   runs-on: ubuntu-latest
   environment: AWS_Demo
   steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Check Folder
        run: ssh Demo_User@ec2-18-230-5-50.sa-east-1.compute.amazonaws.com "cd ${{vars.AWS_PROJECT_PATH}} && dir"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push code to EC2
        run: scp -r . Demo_User@ec2-18-230-5-50.sa-east-1.compute.amazonaws.com:${{vars.AWS_PROJECT_PATH}}

      - name: SSH into EC2 and perform actions
        run: |
          ssh Demo_User@18.230.5.50 "cd ${{vars.AWS_PROJECT_PATH}} && mvn compile test"

  cleanup:
    needs: [build]
    runs-on: windows-latest
    environment: AWS_Demo

    steps:
      - name: Clean-Up
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          password : ${{ secrets.AWS_PASSWORD }}
          scripts: |
            echo ${{vars.AWS_PROJECT_PATH}}
            cd ${{vars.AWS_PROJECT_PATH}}
            Remove-Item '${{vars.AWS_PROJECT_PATH}}\*' -Recurse