name: Continuous Integration to AWS instance.
run-name: Executing CI/CD by ${{github.actor}}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Java 17 installation
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Run tests
        run: mvn clean install

  analyse:
     name: Run security check
     runs-on: windows-latest
     permissions:
       actions: read
       contents: read
       security-events: write

     strategy:
       fail-fast: false
       matrix:
        language: ['java']

     steps:
       - name: Checkout
         uses:  actions/checkout@v3.5.3

       - name: Initialize CodeQL
         uses: github/codeql-action/init@v2
         with:
           languages: ${{matrix.language}}
        # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
       - name: Auto-build
         uses: github/codeql-action/autobuild@v2

       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v2
         with:
            category: "/language:${{matrix.language}}"


  push_to_windows_ec2:
   #needs: [build]
   runs-on: ubuntu-latest
   environment: AWS_Demo
   steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone Repo
        run: |
          git clone https://github.com/abwasha/SamplePOMFramework.git
          cd SamplePOMFramework
          echo %cd%
          mvn clean

  push_to_Linux_ec2:
    runs-on: ubuntu-latest
    environment: AWS_Demo
    steps:
        - name: Checkout
          uses: actions/checkout@v3.5.3


        - name: Copy artifacts to AWS
          uses: appleboy/scp-action@master
          with:
            host: ${{ vars.AWS_LINUX_HOST }}
            username: ${{ vars.AWS_LINUX_USER }}
            key: ${{ secrets.LINUX_SSH_KEY }}
            source: './'
            target: '${{ vars.LINUX_PROJECT_PATH }}'

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ vars.AWS_LINUX_HOST }}
            username: ${{ vars.AWS_LINUX_USER }}
            key: ${{ secrets.LINUX_SSH_KEY }}
            script: | 
              whoami
              ls

        - name: Execute SSH commmands on remote server
          uses: JimCronqvist/action-ssh@master
          with:
            hosts: 'ec2-user@18.229.161.254'
            privateKey: ${{ secrets.LINUX_SSH_KEY }}
            debug: true
            command: ls -lah
      

  cleanup:
    needs: [build]
    runs-on: windows-latest
    environment: AWS_Demo

    steps:
      - name: Clean-Up
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          password : ${{ secrets.AWS_PASSWORD }}
          scripts: |
            echo ${{vars.AWS_PROJECT_PATH}}
            cd ${{vars.AWS_PROJECT_PATH}}
            Remove-Item '${{vars.AWS_PROJECT_PATH}}\*' -Recurse