name: Run tests on Firefox using POM framework
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'workflow_dispatch description : To be run on main branch'
        default: 'main'
        required: true

jobs:
  run-pom-tests:
    name: Job Name - Running Unit tests on POM framework
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install Firefox Browser
        run: |
          #sudo apt-get update
          #sudo apt-get install -y firefox
          #sudo snap remove firefox
          #sudo add-apt-repository ppa:mozillateam/ppa
          #sudo apt install firefox
          #wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US"
          #tar -xvf firefox.tar.bz2
          #sudo mv firefox /opt/
          #sudo ln -s /opt/firefox/firefox /usr/local/bin/
          #sudo chmod +x /usr/local/bin/firefox
          #export PATH=$PATH:/usr/local/bin/firefox

      - name: Install Firefox Driver
        run: |
          # Download and install GeckoDriver
          wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          sudo tar -xzvf geckodriver.tar.gz
          sudo chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          echo "------------------------------"
          cd /usr/local/bin
          pwd
          ls -l
          export PATH=$PATH:/usr/local/bin/geckodriver
          echo $PATH
          java -version
          uname -m
          firefox --version
          geckodriver -V

      - name: Build and run tests
        run: |
          mvn clean install
          # Run your tests using Maven
          mvn test