name: Run tests on default Firefox using POM framework
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'workflow_dispatch description : To be run on main branch'
        default: 'main'
        required: true

jobs:
  run-pom-tests:
    name: Job Name - Running Unit tests on POM framework
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3


      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17 # Use the desired version

      - name: Display Java version
        run: java -version

      - name: Display JAVA_HOME
        run: echo "JAVA_HOME is $env:JAVA_HOME"