name: Run tests on default Firefox using POM framework
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'workflow_dispatch description : To be run on main branch'
        default: 'main'
        required: true

jobs:
  run-pom-tests:
    name: Job Name - Running Unit tests on POM framework
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3


      - name: Build and run tests
        run:
          #firefox --version
          #geckodriver -V
          #export PATH=$PATH:/usr/local/share/gecko_driver
          #echo $PATH
          ping www.google.com ^
          && mvn clean compile test
          # Run your tests using Maven
          #mvn test