name: Run tests on Linux with default Firefox/Chrome using POM framework
run-name: Build by @${{github.actor}}
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'workflow_dispatch description : To be run on main branch'
        default: 'main'
        required: true

jobs:
  run-pom-tests:
    name: Job Name - Running Unit tests on POM framework
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Java 17 installation
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Display Java Mozilla and WebDriver version
        run: |
          java -version
          firefox --version
          geckodriver --version
          google-chrome --version
          chromedriver --version
          

      - name: Display JAVA_HOME
        run: echo "JAVA_HOME is $JAVA_HOME"

      - name: Display Drivers and its paths in runner machine
        run: | 
          cd /usr/local/share
          ls -l

      - name: Run test
        run: mvn clean compile test