name: Run tests on POM framework
on:
   push:
     branches: 'feature/*'
jobs:
  run-pom-tests:
    name: Running Unit tests on POM framework
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/actions/checkout@v3.5.3
      - name: run tests
        run: mvn clean compile test
    
