name: Run tests on POM framework
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'workflow_dispatch description : To be run on main branch'
        default: 'main'
        required: true

jobs:
  run-pom-tests:
    name: Job Name - Running Unit tests on POM framework
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

          # Download and install GeckoDriver
          wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          sudo tar -xzvf geckodriver.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          geckodriver -V
          cd /usr/local/bin
          ls -l
          export PATH=$PATH:/usr/local/bin/geckodriver
          echo $PATH
          echo "------------------------------"
          java -version
          uname -m
          firefox --version

      - name: Build and run tests
        run: |
          mvn clean install
          # Run your tests using Maven
          mvn test