name: Run unit test of feature branch

on:
  pull_request:
    branches:
      - 'feature/*'
    types:
      - opened
jobs:
  define-environment:
    name: 'Running and uploading surefire reports to the artifacts'
    runs-on: windows-latest

    steps:
      - name: Pull Request Title Validation
        # You may pin to the exact commit or the version.
        # uses: skimit/validate-pull-request-title-github-action@c01022ed4f3938898271e9660174e6b5a6daaa8e
        uses: skimit/validate-pull-request-title-github-action@v1.1.0
        with:
          # Pull Request Title
          pr-title: 'Abdul PR - '
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Java 17 installation
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Run test on push event
        run: mvn clean compile test

      - name: Upload reports
        uses: actions/upload-artifact@v3.1.2
        with:
          name: surefire-reports
          path: ./target/surefire-reports