name: Run tests on Windows with default Firefox/Chrome using POM framework
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'workflow_dispatch description : To be run on main branch'
        default: 'main'
        required: true

jobs:
  run-pom-tests:
    name: Job Name - Running Unit tests on POM framework
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Java installation
        uses: actions/setup-java@v3
        with:
            distribution: 'oracle' # See 'Supported distributions' for available options
            java-version: '17'
            cache: 'maven'

      - name: Display Java version
        run: java -version

      - name: Display JAVA_HOME
        run: echo "JAVA_HOME is $env:JAVA_HOME"

      - name: Run test
        run: mvn clean compile test